rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - tip

gemfile:
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile

before_install:
  - gem install bundler -v 1.17.3

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
